path.data: /var/lib/elasticsearch
network.host: 0.0.0.0
http.port: 9200
indices.query.bool.max_clause_count: 40096
indices.memory.index_buffer_size: 10%
path.repo: ["/usr/share/elasticsearch/backup"]
xpack.security.enabled: false
